services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: arbeit-frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    environment:
      NODE_ENV: production
    networks:
      - arbeit-network
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: arbeit-backend
    ports:
      - "9090:9090"

    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: "-Xmx512m -Xms256m"
      SERVER_PORT: 9090
    networks:
      - arbeit-network
    restart: unless-stopped

networks:
  arbeit-network:
    driver: bridge
