apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arbeit-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    # Frontend
    - host: arbeit.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arbeit-frontend-service
                port:
                  number: 80

    # Backend
    - host: api.arbeit.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arbeit-backend-service
                port:
                  number: 9090