resources:
  - backend-configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-secret.yaml
  - frontend-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - mysql-deployment.yaml
